fn main() {
    // Creating a new String 

    // many of the operations available with Vec<T> are also available with String , because String is actually implemented as a wrapper around bytes 
    let mut s = String::new();

    let data = "initial contents";

    // the emthod also works on a literal direclty - we can use to_string to create a string from a string literal 
    let s = data.to_string();

    // we cna also use String::from
    let s = String::from("intitial contents");

    // remember strings are encoded , so we can include any properly encoded data in them 
        let hello = String::from("السلام عليكم");
    let hello = String::from("Dobrý den");
    let hello = String::from("Hello");
    let hello = String::from("שָׁלוֹם");
    let hello = String::from("नमस्ते");
    let hello = String::from("こんにちは");
    let hello = String::from("안녕하세요");
    let hello = String::from("你好");
    let hello = String::from("Olá");
    let hello = String::from("Здравствуйте");
    let hello = String::from("Hola");

    //updating a String 
    // A string can grow in size just like the contents of a Vec<T> , if you push more data into it . In addition, you can us the + operator or the format! macro to concatenate String values 
    let mut s = String::from("foo");
    s.push_str("bar");
    // after these two lines , s would contain foobar

    let mut s1 = String::from("foo");
    let s2 = "bar";
    s1.push_str(s2);

    println!("s2 is {s2}");
    // the push_str method didn't take ownership of s2 so thats why we are able to print its value on the next line 

    let mut s = String::from("lo");

    s.push('l');

    //concatentation with the +Operator or the format! Macro 

    //we can only add an String value to a &str , we cannot add a String to a String , hence thats why we declared s1 and s2 the way we declared it 
    //   the implementation of thre + sign  has a signature like this 
    // fn add(self, s:&str) -> String so s2 is the s in this fn
    // but the type &String is not the allowed type in our fn which is &str , so why does it compile?
    // well &String can be compiled into &Str, when we call the add mehtod , rust uses a deref coercion , which here turns &s2 into &s2[..] , and add does not take ownership of the s parameter, s2 will still be a valid String after the operation
    // so here , the add function takes owenership of self becaue self doe not have a &, so its value is moved into the add fn , here it is s1, so even though we are concatenating both strings together, we are taking ownership of s1 value , then appending a copy of the contents of s2 to it and returns ownership of the result 

    // let s1 = String::from("Hello,");
    // let s2 = String::from("world");
    // let s3 = s1 + &s2;
    
    // of we need to concatenate multiple strings , the behaviour of the + operator gets unwieldy 
    // let s1 = String::from("tic");
    // let s2 = String::from("tac");
    // let s3 = String::from("toe");

    // let s = s1 + "-" + &s2 + "-" + &s3;
    let s4 = String::from("tic");
    let s5 = String::from("tac");
    let s6 = String::from("toe");

    // instead of this for more compilcated string formatting use the format! macro
    // also the code generated by the format macro uses references sop no need to worry about ownership or variables
    let s = format!("{s4}-{s5}-{s6}");

    //indexing into Strings
    // if you try to access string characters in rust like you do in other languages you are goin to get an error 
    let s1 = String::from("hello");
    // let h = s1[0];
//     the type `String` cannot be indexed by `{integer}`
// the trait `Index<{integer}>` is not implemented for `String`
// the following other types implement trait `Index<Idx>`:
//   <String as Index<RangeFull>>
//   <String as Index<std::ops::Range<usize>>>
//   <String as Index<RangeFrom<usize>>>
//   <String as Index<RangeTo<usize>>>
//   <String as Index<RangeInclusive<usize>>>
//   <String as Index<RangeToInclusive<usize>>>
// rust strings don't support indexing 

//Internal representation 
// A String is a wrapper over a Vec<u8> 
// for our properly encoded UTF-8 String the length here would be 4 
let hello = String::from("Hola");

// Each of these letters takes 1 byte when encoded in UTF-8. The following line, however, may surprise you. (Note that this string begins with the capital Cyrillic letter Ze, not the number 3.)

let hello = String::from("Здравствуйте");

// when asked the length, you might say 12 , but its actually 24 , thats the number of bytes it takes ot encode ,  “Здравствуйте” in UTF-8, because each Unicode scalar value in that string takes 2 bytes of storage, so an index into the string's bytes will not always correlate to a valid Unicode scalar value 

// let hello = "Здравствуйте";
// let answer = &hello[0];

//You already know that answer will not be З, the first letter. When encoded in UTF-8, the first byte of З is 208 and the second is 151, so it would seem that answer should in fact be 208, but 208 is not a valid character on its own. Returning 208 is likely not what a user would want if they asked for the first letter of this string; however, that’s the only data that Rust has at byte index 0. Users generally don’t want the byte value returned, even if the string contains only Latin letters: if &"hello"[0] were valid code that returned the byte value, it would return 104, not h.

//Bytes and Scalar values and Grapheme Clusters
// A point about UTF 8 is that there are three relevant ways to look at strings from rusts pperspectives 
// the hindi word “नमस्ते” written in the Devanagari script, it is stored as a vector of u8 values that looks like this

//[224, 164, 168, 224, 164, 174, 224, 164, 184, 224, 165, 141, 224, 164, 164,
// 224, 165, 135], thats 18 bytes and this is how computers store data 

// That's 18 bytes and is how computers ultimately store this data, if we look at them as Unicode scalar values, which are what Rust's char type is , those bytes look like this 

// ['न', 'म', 'स', '्', 'त', 'े']
// There are six char values here, but the fourth and sixth are not letters: they’re diacritics that don’t make sense on their own. Finally, if we look at them as grapheme clusters, we’d get what a person would call the four letters that make up the Hindi word:


// ["न", "म", "स्", "ते"]

// a final reason that rust doesn't allow us index into a string to get a character is that indexing operations are expected to always take constant time O(1) , but its impossible to guarantee that because we would have to walk throgh the contents from the beginning to the index to determine how many valid characters there were 

//Slicing Strings 
//indexing with a string is a bad thing to do because we are not sure whether the return type  grapheme cluster , a character, byte value 

let hello = "Здравствуйте";

let s = &hello[0..4];

//Here s will be a &str that contains the first 4 bytes of the string, earlier we mentioned that each of the characters was 2 bytes, which means s will be Зд

// but if we were to try to slice only part of a characters's bytes with something like &hello[0..1] , rust would panic at runtime in the same way as if an invalid index were accessed in a vector 
// methods for iterating over strings

for c in "Зд".chars() {
    println!("{c}");
}

// but appropriately the bytes returns each raw byte might be appropriate for your domain 

for b in "Зд".bytes() {
    println!("{b}");
}
// But be sure to remember that valid Unicode scalar values may be made up of more than 1 byte.

// Getting grapheme clusters from strings as with the Devanagari script is complex, so this functionality is not provided by the standard library. Crates are available on crates.io if this is the functionality you need.

// in summary Strings are complicated 
}
